apiVersion: v1
kind: Service
metadata:
  name: reqres-service
spec:
  ports:
    - name: reqres
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  type: NodePort
  selector:
    app: reqres